SELECT DISTINCT A.ATIVO,
C.ITEMIMOBILIZADO AS ITEM_IMOBILIZADO,
A.CODIGOREFERENCIA AS CODIGO_REFERENCIA,
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(A.NOME ,char(13),''),char(34),''),char(9),''),char(10),''),'/N','/ N'),'/R','/ R') AS NOME_DO_ITEM,
B.FAMILIA AS ESTRUTURA_FAMILIA,
B.NOME AS NOME_FAMILIA,
A.DATAINCLUSAO AS DATA_DE_INCLUSAO,
EMP.NOME AS NOME_EMPRESA,
ZGU_INCLUIU.NOME AS NOME_USUARIO_INCLUSAO

FROM PD_PRODUTOSPAI A
LEFT JOIN PD_FAMILIASPRODUTOS B ON B.HANDLE = A.FAMILIA
LEFT JOIN PD_PRODUTOS C ON C.CODIGOREFERENCIA = A.CODIGOREFERENCIA
INNER JOIN CM_UNIDADESMEDIDA D ON D.HANDLE = C.UNIDADEMEDIDACOMPRAS
LEFT JOIN EMPRESAS EMP ON A.EMPRESA = EMP.HANDLE
LEFT JOIN Z_GRUPOUSUARIOS ZGU_INCLUIU ON ZGU_INCLUIU.HANDLE = A.USUARIOINCLUIU