SELECT DISTINCT EMP.NOME AS NOME_EMPRESA,
E.NOME AS NOME_FILIAL,
B.NUMERO AS NUMERO_CONTRATO,
CASE WHEN G.TIPO = '1' THEN 'À PAGAR' ELSE
    CASE WHEN G.TIPO = '2' AND G.K_EHNAOFINANCEIRO = 'S' THEN 'NÃO FINANCEIRO' ELSE
        CASE WHEN G.TIPO = '2' AND G.K_EHNAOFINANCEIRO = 'N' THEN 'À RECEBER' ELSE
            CASE WHEN G.TIPO = '3' THEN 'CONVÊNIOS'
            END
        END
    END
END AS 'TIPO_CONTRATO',

B.DATAINCLUSAO AS DATA_INCLUSAO_CONTRATO,
B.DATAINICIO AS INICIO_VIGENCIA,
B.DATAFIM AS FINAL_DA_VIGENCIA,
CASE WHEN ZGU_NEGOCIOU.APELIDO IS NULL THEN UPPER(ZGU_INCLUIU.APELIDO) ELSE UPPER(ZGU_NEGOCIOU.APELIDO) END AS COMPRADOR,
ZGU_INCLUIU.APELIDO AS USUARIO_INCLUSAO,
ZGU_NEGOCIOU.APELIDO AS USUARIO_NEGOCIOU,
F.CGCCPF AS CNPJ_FORNECEDOR,
F.NOME AS NOME_FORNECEDOR,
CASE WHEN B.K_PARECERTECNICO ='S' THEN 'SIM' ELSE
    CASE WHEN B.K_PARECERTECNICO IS NULL THEN 'NAO_INFORMADO' ELSE 'NÃO' END
END AS PARECER_TECNICO,


CASE WHEN B.SITUACAO = '1' THEN 'APROVADO' ELSE
     CASE WHEN B.SITUACAO = '2' THEN 'CADASTRO INICIAL' ELSE
         CASE WHEN B.SITUACAO = '3' THEN 'CANCELADO' ELSE
            CASE WHEN B.SITUACAO = '4' THEN 'EM FASE DE ELABORAÇÃO' ELSE
                CASE WHEN B.SITUACAO = '5' THEN 'ENCERRADO' ELSE
                    CASE WHEN B.SITUACAO = '6' THEN 'REJEITADO' ELSE
                        CASE WHEN B.SITUACAO = '8' THEN 'VOLTAR PARA CADASTRO INICIAL' ELSE
                           CASE WHEN B.SITUACAO = '9' THEN 'LIBERADO PARA ASSINATURA' ELSE
                                    CASE WHEN B.SITUACAO = '10' THEN 'CONFIRMADO'
                                    END
                           END
                        END
                    END
                END
            END
         END
     END
END AS STATUS_CONTRATO,
H.CODIGO AS CODIGO_ITEM,

UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(B.OBJETOCONTRATO ,char(13),' - '),char(9),''),char(10),''),'/N','/ N'),'/R','/ R')) AS OBJETO_DO_CONTRATO



FROM CN_CONTRATOS B
LEFT JOIN FILIAIS E ON E.HANDLE = B.FILIAL
LEFT JOIN EMPRESAS EMP ON E.EMPRESA = EMP.HANDLE
LEFT JOIN GN_PESSOAS F ON F.HANDLE = B.PESSOA
LEFT JOIN CN_TIPOSCONTRATOS G ON G.HANDLE = B.TIPOCONTRATO
LEFT JOIN Z_GRUPOUSUARIOS ZGU_INCLUIU ON ZGU_INCLUIU.HANDLE = B.USUARIOINCLUIU
LEFT JOIN Z_GRUPOUSUARIOS ZGU_NEGOCIOU ON ZGU_NEGOCIOU.HANDLE = SUBSTRING(K_USUARIONEGOCIOU,0,CHARINDEX('|',K_USUARIONEGOCIOU))
LEFT JOIN CP_CONDICOESPAGAMENTO CC ON CC.HANDLE = B.CONDICAOPAGAMENTODEFAULT
LEFT JOIN CN_CONTRATOOBJETOS COMP ON COMP.CONTRATO = B.HANDLE
LEFT JOIN PD_PRODUTOS H ON H.HANDLE = COMP.PRODUTO
LEFT JOIN CN_CONTRATOFILIAIS RR ON RR.CONTRATO = B.HANDLE

WHERE B.SITUACAO IN ('1','2','4','5','8','9','10') AND YEAR(B.DATAINCLUSAO) >= 2019